
spring:
 boot:
    admin:
      client:
        url: http://localhost:2222/

 datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/majorProject
    username: root
 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
 
server:
  port: 8081
  
auth-service:
messages:
reg : sucessfully registred
regErr : registration failed
login : sucessfully logedin
loginErr : invalid credentials  
  
